### ISSUE TITLE
Merge into `hoplon/hoplon`

### ISSUE THREAD

**Issue by onetom** [tailrecursion/boot-hoplon#10]
On Slack there were discussions about merging `boot-holpon` into `hoplon`.
This issue is here to discuss the pros and cons.

The main issue is the bidirectional dependence of the runtime and the compile time.
(example needed)

One con is being able to distribute Hoplon libraries without pulling in `boot-hoplon` too as a dependency.

A middle road could be:

> it occured to me we could have an "easy" option, a 3rd artifact that just depends on boot-hoplon and hoplon
> e.g. boot-pack or smth 
> then we have the ease of a single artifact, but retain the flexibility to specify different task/runtime versions

-- @alandipert [source](https://clojurians-log.clojureverse.org/hoplon/2016-10-25.html)

**Comment by burn2delete** [comment]
I think this is easy to resolve, we can bump the major version of both projects and make them interdependent in different scopes.

Ex. 
Boot-Hoplon(v1.0) depends on Hoplon(v7?) in compile scope
Hoplon(v7) depends on Boot-Hoplon(v1.0) in test scope

Most users will specify both in their boot files, users have the option of only specifying hoplon.

Users who are not using the boot task will need to specify `hoplon.jquery` or `hoplon.goog` anyway.

The issue comes into play if you attempt to build hoplon with an old version of boot-hoplon, where the user would also need to include `hoplon.jquery`
If the user upgrades the boot-task without updating hoplon they will get an error about a not being able to find `hoplon.jquery`.

As an alternative we could move boot-hoplon to the "provided" scope to avoid pulling the dependency.

**Comment by burn2delete** [comment]
This has happened already.
